pipeline:
  identifier: Build_jensh00_tala2app_1705442155859
  name: Build tala2app
  orgIdentifier: default
  projectIdentifier: projectjensh
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1705442138716
        repoName: jensh00/tala2app
        build: <+input>
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    shell: Sh
                    command: ls
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
        description: ""
